# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: AMA ESLint

defaults:
  run:
    working-directory: loama

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: latest
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        id: cache
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        name: Setup PNPM cache
        env:
          STORE_PATH: ${{ steps.cache.outputs.STORE_PATH }}
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install ESLint
        run: |
          pnpm install eslint@8.10.0
          pnpm install @microsoft/eslint-formatter-sarif@2.1.7
      - name: Run ESLint
        run: pnpm exec eslint .
          --config .eslintrc.cjs
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
